### ISSUE TITLE
(how to create own server?)

### ISSUE THREAD

**Issue by txdnation** [CodeStix/FNAFOnline#6]
I have already run the source with unity the problem is always when I open the exe file it gets stuck at 60% how can I create my own server? Can you please help me thank you:)

**Comment by CodeStix** [comment]
You could run your own server, however, your friends won't be able to join you because you can't connect to a custom server in the public build. 

You can connect to it during development however:
1. Build the project in `Server/Stx.Net`.
2. Start the server in `Server/Stx.Net/StxServer/Build/Debug(or Release)/Stx.ServerProgram.exe`
3. Adjust the connection url in the StxUnityClient component in Core.scene.
4. Play

I am currently working on a new server system (because the system is crap 😐), including complete rework of the office and a new gamemode. So I suggest you just wait for the next release (expect a week) 🙂, which will improve the multiplayer system a lot.
